-- Enable trigram similarity for fuzzy comparable-title FK resolution.
-- Per ADR-0027 follow-up: bulk extraction smoke surfaced ~26% of LLM-produced
-- comparable strings failing case-insensitive exact match against titles.title.
-- A meaningful fraction of those are name-shape mismatches ("Demon Slayer"
-- vs "Demon Slayer: Kimetsu no Yaiba"), not catalog gaps. Trigram similarity
-- catches them cheaply without needing the full pgvector embedding pipeline
-- (which is Phase 2 work for viewer_pleasures + comparable in one go).
--
-- This migration is manually authored (not generated by drizzle-kit) because
-- drizzle-kit doesn't model Postgres extensions in the schema layer. The
-- index uses an expression (LOWER(title)) with gin_trgm_ops which is also
-- outside Drizzle's index() helper.
--
-- pg_trgm provides:
--   - similarity(text, text) → real
--   - operator %  (default threshold 0.3)
--   - operator <-> (distance)
-- The GIN index speeds up % and similarity() queries; at 5,949 rows the
-- index is near-instant to build (<1s) and pays for itself even at this
-- scale because the fuzzy fallback runs once per unresolved comparable.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "titles_title_trgm_idx"
  ON "titles" USING gin (LOWER(title) gin_trgm_ops);
